version: "2"

services:
    app:
        build:
            context: docker/dev
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
            - /app/var/cache
            - /app/var/sessions

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:3.2

    rabbitmq:
        image: rabbitmq:3-management
